routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('dashboard');   
})->middleware('auth');



Route::get('invite', 'InviteController@invite')->name('invite')->middleware('auth');
Route::post('invite', 'InviteController@process')->name('process')->middleware('auth');
Route::get('accept/{token}', 'InviteController@accept')->name('accept');


Route::get('dashboard', 'DashboardController@index')->middleware('auth');
Route::resource('tasks', 'TasksController')->middleware('auth');
Route::post('tasks/updateStatus/{id}', 'TasksController@updateStatus')->name('tasks.updateStatus')->middleware('auth');
Route::post('tasks/assignUser/{id}', 'TasksController@assignUser')->name('tasks.assignUser')->middleware('auth');

Route::resource('meetings', 'MeetingController')->middleware('auth');
Route::resource('users', 'UsersController')->middleware('auth');
Route::resource('companies', 'CompanyController')->middleware('auth');
Route::resource('subjects', 'SubjectController')->middleware('auth');
Route::post('subjects/updateStatus/{id}', 'SubjectController@updateStatus')->name('subjects.updateStatus')->middleware('auth');

Auth::routes();
Route::get('register.admin', 'Auth\RegisterController@admin')->name('register.admin');
Route::post('register.createAdmin', 'Auth\RegisterController@createAdmin')->name('register.createAdmin');

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id', 'company_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function task()
    {
       return $this->hasMany(Task::class);
    }

    public function meeting()
    {
        return $this->hasMany(Meeting::class);
    }
    public function roles()
    {
        return $this->belongsToMany(Role::class, 'role_user');
        // return $this->hasMany(Role::class, 'role_user', 'user_id');
    }
    public function hasAnyRoles($roles)
    {       
        return null !== $this->roles()->whereIn('name', $roles)->first();
    }
    public function meetings()
    {
        return $this->belongsToMany(Meeting::class, 'meeting_user');
    }
    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function hasRole($role)
    {
        $isRole =  User::whereHas('roles', function($q) use($role){
            $q->whereRoleId($role);
        })->get();

        return $isRole;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use  \App\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = User::all();
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User();
        $roles = \App\Role::all();
        return view('users.create', compact('user', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validated = $this->validateRequest();
            if($validated['role_id'] == "0"){
            $validated['role_id'] = 2;
        }
        $validated['company_id'] = auth()->user()->company_id;
        // Create hash for user password
        $validated['password'] = Hash::make($validated['password']);
        $user = User::create($validated);
        $user->roles()->attach([2]);
        return redirect('users');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $user = User::findOrFail($id);
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = User::findOrFail($id);
        $roles = \App\Role::all();
        return view('users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,User $user)
    {
        
        $validated = request()->validate([
            'name' => 'required|min:5',
            "email" => "required|email",
            'role_id' => 'integer',
        ]);

        if(!$request->password){
            $validated['password'] = $user->password; // Same password
        }else{ // Changed password
            $validated['password'] = Hash::make($request->password);
        }
        $user->update($validated);
        return view('users.show', compact('user'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $user = User::findOrFail($id);
        $user->delete();

        return redirect('users');
    }

    public function validateRequest()
    {
        return request()->validate([
            'name' => 'required|min:5',
            "email" => "required|email",
            'role_id' => 'integer',
            "password" => 'required|min:8|confirmed', ///different:current_password|
        ]);
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', 'Create New User')

@section('content')

<div class="row py-3">
    <h1> Create New User </h1>
    <hr>
</div>
<div class="row">
    <form action="{{ route('users.store') }}" method="post" enctype="multipart/form-data">
        @include('users.form')
        <button type="submit" class="btn btn-success">Create</button>
    </form>
</div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Users')

@section('content')

<div class="row py-3">
    <h1> Edit Users </h1>
    <hr>
</div>
<div class="row">
    <form action="{{ route('users.update', ['user'=> $user ]) }}" method="post" enctype="multipart/form-data">
        @method('PATCH')
        @include('users.form')
        <button type="submit" class="btn btn-success">Update</button>
    <a href="{{url('users')}}" class="btn btn-link">Cancel</a>
    </form>
</div>

@endsection

resources/views/users/form.blade.php
@foreach ($errors->all() as $message)
<div class="alert alert-danger">
    <strong>Error!</strong>
    {{ $message }}
</div>
@endforeach
<div class="form-group">
    <label for="name">User name</label>
    <input type="text" class="form-control" name="name" id="name" value="{{ old('name') ?? $user->name }}" autofocus>
    @if($errors->first('name'))
    <div class="alert alert-danger">
        <strong>Error!</strong>
        {{ $errors->first('name')}}
    </div>
    @endif
</div>
{{-- @if(Request::is('*/create')) --}}
<div class="form-group">
    <label for="role_id">User Role</label>
    <select name="role_id" id="role_id" class="form-control custom-select">
        <option value="0">Select Role for user</option>
        @foreach ($roles as $role)
    <option value="{{old('role_id') ?? $role->id}}"
         {{ old('role_id')  == $role->id || $user->role_id == $role->id ? 'selected': ''}}>{{ $role->name}}</option>
            
        @endforeach
    </select>
</div>
{{-- @endif --}}
<div class="form-group">
    <label for="registration_key">Registration Key</label>
    <p class="form-control">
        {{isset($user->company)?$user->company->registration_link:'No link here'}}
    </p>
</div>

<div class="form-group">
        <label for="email">Registration mail</label>
        <input type="email" class="form-control" name="email"
value="{{ old('email')?? $user->email }}"
        />
    </div>
@if(Request::is('*users/create') || Request::is('*users/*/edit'))
    <div class="form-group">
            <label for="password">Password</label>
            <input class="form-control" type="password"
                name="password" id="password"
            />
    </div>
    <div class="form-group">
            <label for="password-confirm">Password Confirm</label>
            <input class="form-control" type="password"
                name="password_confirmation" id="password-confirm"
            />
    </div>
@endif


@csrf

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', 'User List')

@section('content')

<div class="row py-3">
  <h1> Users List </h1>
  <hr>
  <a href="{{asset('/users/create')}}" role="button" class="btn btn-success btn-lg">Add user</a>
</div>
<div class="row">
  <table class="table  table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">User</th>
        <th scope="col">Role</th>
        <th scope="col">Company</th>
        <th scope="col">Manage</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($users as $user)
      @if(auth()->user()->company_id == $user->company_id)
      {{-- @can('view', $user, \App\User::class) --}}
      <tr>
        <th scope="row"> {{$user->id}} </th>
        <td>
          {{$user->name}}
        </td>
        <td>
          @foreach ($user->roles as $role)
        <span style="font-size:.875em" class="badge badge-primary">{{$role->name}}</span>
          @endforeach
        </td>
        <td>
          {{isset($user->company) ? $user->company->name : 'No company'}}
        </td>
        <td>
            <a class="btn btn-info" href="users/{{ $user->id }}" role="button">
              <i class="fa fa-eye"></i>
            </a>
          <a class="btn btn-success" href="users/{{ $user->id }}/edit" role="button">
            <i class="fa fa-pencil"></i>

          </a>
        <button class="btn btn-danger btn-sm deleteMe" data-user-id="{{ $user->id }}" role="button">
            <i class="fa fa-trash"></i>
          </button>

        </td>
      </tr>
      @endif
      @endforeach
    </tbody>
  </table>

  <script type="application/javascript">
    $(document).ready(function(){
      console.log('ready to work')
       $('.deleteMe').on('click', function(){
         console.log('Clicked: ' +'/users/' + $(this).attr('data-user-id'));
          $.ajax({
            url: "{{url('users')}}/" + $(this).attr('data-user-id'),
            type: 'DELETE',
            headers: {
              "X-CSRF-TOKEN": "{{ csrf_token() }}",
            },
            success: function(){
              window.location.href = "users";
            },
            error: function(){
              window.location.href = "users";
            }
          });
       })     
    });
</script>
</div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('title', 'user')

@section('content')

<div class="row py-3">
    <h1> Details for user #{{ $user->id}} </h1>
    <hr>
</div>

<div class="row">
    <div class="col-12">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    Details for user #{{ $user->id}}
                </div>

                <ul class="list-group list-group-flush">
                    <li class="list-group-item"> <strong>User name</strong>
                        {{ $user->name }}
                    </li>
                    <li class="list-group-item"> <strong>User mail</strong>
                        {{ $user->email }}
                    </li>
                    <li class="list-group-item">
                        <strong>User Roles</strong>
                        @foreach ($user->roles as $role)
                        <h5>
                            <span class="badge badge-primary">{{ $role->name}} </span>
                        </h5>
                        @endforeach
                    </li>
                    <li class="list-group-item">
                        <strong>Company</strong>
                        {{ isset($user->company) ? $user->company->name : 'No company'}}
                    </li>
                </ul>
                <div class="card-footer">
                    <a href="{{url('users')}}" class="btn btn-link pull-left" role="button">Back</a>
                    <a href="{{ route('users.edit', ['user'=> $user ]) }}" class="btn btn-success pull-left"
                        role="button">
                        <i class="fa fa-pencil"></i>
                    </a>

                    <form class="form-inline" action="{{ route('users.destroy', ['user'=> $user ]) }}" method="post"
                        enctype="multipart/form-data">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-danger">
                            <i class="fa fa-trash"></i>
                        </button>
                    </form>
                </div>
            </div>

        </div>

    </div>
</div>

@endsection