routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('dashboard');   
})->middleware('auth');



Route::get('invite', 'InviteController@invite')->name('invite')->middleware('auth');
Route::post('invite', 'InviteController@process')->name('process')->middleware('auth');
Route::get('accept/{token}', 'InviteController@accept')->name('accept');


Route::get('dashboard', 'DashboardController@index')->middleware('auth');
Route::resource('tasks', 'TasksController')->middleware('auth');
Route::post('tasks/updateStatus/{id}', 'TasksController@updateStatus')->name('tasks.updateStatus')->middleware('auth');
Route::post('tasks/assignUser/{id}', 'TasksController@assignUser')->name('tasks.assignUser')->middleware('auth');

Route::resource('meetings', 'MeetingController')->middleware('auth');
Route::resource('users', 'UsersController')->middleware('auth');
Route::resource('companies', 'CompanyController')->middleware('auth');
Route::resource('subjects', 'SubjectController')->middleware('auth');
Route::post('subjects/updateStatus/{id}', 'SubjectController@updateStatus')->name('subjects.updateStatus')->middleware('auth');

Auth::routes();
Route::get('register.admin', 'Auth\RegisterController@admin')->name('register.admin');
Route::post('register.createAdmin', 'Auth\RegisterController@createAdmin')->name('register.createAdmin');

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
    protected $guarded = [];

    public function users()
    {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CompanyController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $this->authorize('view', auth()->user(),\App\Company::class);
        $companies = Company::all();
        return view('companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $this->authorize('create', \App\Company::class);
        $company = new Company();
        return view('companies.create', compact('company'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $this->authorize('create', \App\Company::class);
        $validated = $this->validateRequest();
        $validated['registration_link'] = (string) Str::uuid(); 
        $company = Company::create($validated);

        return redirect('companies');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $this->authorize('view', auth()->user(), \App\Company::class);
        $company = Company::findOrFail($id);
        return view('companies.show', compact('company'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $company = Company::find($id);
        return view('companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $company = Company::findOrFail($id);
        $company->update($this->validateRequest());

        return redirect('companies/' . $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::findOrFail($id);
        $company->delete();

        return redirect('/companies');
    }

    public function validateRequest()
    {
        return request()->validate([
            'name' => 'required|min:5',
            "mail_domain" => 'required|email', 
            // "status" => "required",
        ]);
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('title', 'Create New Company')

@section('content')

<div class="row py-3">
    <h1> Create New company </h1>
    <hr>
</div>
<div class="row">
    <form action="{{ route('companies.store') }}" method="post" enctype="multipart/form-data">
        @include('companies.form')
        <button type="submit" class="btn btn-success">Create</button>
    </form>
</div>

@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Company')

@section('content')

<div class="row py-3">
    <h1> Edit Company </h1>
    <hr>
</div>
<div class="row">
    <form action="{{ route('companies.update', ['company'=> $company ]) }}" method="post" enctype="multipart/form-data">
        @method('PATCH')
        @include('companies.form')
        <button type="submit" class="btn btn-success">Update</button>
    <a href="{{url('companies')}}" class="btn btn-link">Cancel</a>
    </form>
</div>

@endsection

resources/views/companies/form.blade.php
@foreach ($errors->all() as $message)
<div class="alert alert-danger">
    <strong>Error!</strong>
    {{ $message }}
</div>
@endforeach
<div class="form-group">
    <label for="name">Company name</label>
    <input type="text" class="form-control" name="name" id="name" value="{{ old('name') ?? $company->name }}" autofocus>
    @if($errors->first('name'))
    <div class="alert alert-danger">
        <strong>Error!</strong>
        {{ $errors->first('name')}}
    </div>
    @endif
</div>

<div class="form-group">
    <label for="mail_domain">Company mail domain</label>
    <input type="email" name="mail_domain" id="mail_domain" class="form-control" value="{{old('mail_domain') ?? $company->mail_domain}}"/>
    @if($errors->first('mail_domain'))
    <div class="alert alert-danger">
        <strong>Error!</strong>
        {{ $errors->first('mail_domain')}}
    </div>
    @endif
</div>
<div class="form-group">
    <label for="registration_key">Registration Key Auto Generated</label>
    <p class="form-control">
            {{old('registration_link') ?? $company->registration_link}}
    </p>
</div>


@csrf

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('title', 'Company Details')

@section('content')

<div class="row py-3">
  <h1> Companies Details </h1>
  <hr>
</div>
<div class="row">
  <table class="table  table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Company</th>
        <th scope="col">Registration Link</th>
        <th scope="col">Manage</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($companies as $company)
      @can('view',$company)
      <tr>
        <th scope="row"> {{$company->id}} </th>
        <td>
          {{$company->name}}
        </td>
        <td title="Click to copy">
          <input type="text" class="selectLink"
              value="{{$company->registration_link}}" readonly/> &nbsp;
          <span class="badge badge-success copyLink" data-company-link="{{$company->registration_link}}">
              Click to copy
          </span>
        </td>
        <td>
            <a class="btn btn-info" href="companies/{{ $company->id }}" role="button">
              <i class="fa fa-eye"></i>
            </a>

          <a class="btn btn-success" href="companies/{{ $company->id }}/edit" role="button">
            <i class="fa fa-pencil"></i>

          </a>
        <button class="btn btn-danger btn-sm deleteMe" data-company-id="{{ $company->id }}" role="button">
            <i class="fa fa-trash"></i>
          </button>

        </td>
      </tr>
      @endcan
      @endforeach
    </tbody>
  </table>

  <script type="application/javascript">
    $(document).ready(function(){
       $('.deleteMe').on('click', function(){
         console.log('Clicked: ' +'/companies/' + $(this).attr('data-company-id'));
          $.ajax({
            url: "{{url('companies')}}/" + $(this).attr('data-company-id'),
            type: 'DELETE',
            headers: {
              "X-CSRF-TOKEN": "{{ csrf_token() }}",
            },
            success: function(){
              window.location.href = "companies";
            },
            error: function(){
              window.location.href = "companies";
            }
          });
       })
       $('.copyLink').on('click',function(){
          var link = $(this).parent().find('.selectLink')
          link.focus();
          link.select();
          document.execCommand('copy');
          var txt = $(this).text() // Click to copy
          $(this).removeClass('badge-success').addClass('badge-light')
          $(this).text(txt.replace('copy', 'copied'))
       })    
    });
</script>
</div>

@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('title', 'Company')

@section('content')

<div class="row py-3">
    <h1> Details for company #{{ $company->id}} </h1>
    <hr>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                Details for company #{{ $company->id}}
            </div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Company name</strong>
                    {{ $company->name }}
                </li>
                <li class="list-group-item">
                    <strong>Registration link</strong>
                    {{ old('registration_link')??$company->registration_link}}
                </li>
                <li class="list-group-item">
                    <strong>Company</strong>
                    {{ old('mail_domain') ?? $company->mail_domain }}
                </li>
            </ul>
            <div class="card-footer">
            <a href="{{url('companies')}}" class="btn btn-link pull-left" role="button">Cancel</a>
                <a href="{{ route('companies.edit', ['company'=> $company ]) }}" class="btn btn-success pull-left"
                    role="button">
                    <i class="fa fa-pencil"></i>
                </a>

                <form class="form-inline" action="{{ route('companies.destroy', ['company'=> $company ]) }}"
                    method="post" enctype="multipart/form-data">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-danger">
                        <i class="fa fa-trash"></i>
                    </button>
                </form>
            </div>
        </div>

    </div>
</div>

@endsection