routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('dashboard');   
})->middleware('auth');



Route::get('invite', 'InviteController@invite')->name('invite')->middleware('auth');
Route::post('invite', 'InviteController@process')->name('process')->middleware('auth');
Route::get('accept/{token}', 'InviteController@accept')->name('accept');


Route::get('dashboard', 'DashboardController@index')->middleware('auth');
Route::resource('tasks', 'TasksController')->middleware('auth');
Route::post('tasks/updateStatus/{id}', 'TasksController@updateStatus')->name('tasks.updateStatus')->middleware('auth');
Route::post('tasks/assignUser/{id}', 'TasksController@assignUser')->name('tasks.assignUser')->middleware('auth');

Route::resource('meetings', 'MeetingController')->middleware('auth');
Route::resource('users', 'UsersController')->middleware('auth');
Route::resource('companies', 'CompanyController')->middleware('auth');
Route::resource('subjects', 'SubjectController')->middleware('auth');
Route::post('subjects/updateStatus/{id}', 'SubjectController@updateStatus')->name('subjects.updateStatus')->middleware('auth');

Auth::routes();
Route::get('register.admin', 'Auth\RegisterController@admin')->name('register.admin');
Route::post('register.createAdmin', 'Auth\RegisterController@createAdmin')->name('register.createAdmin');

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    //
    protected $guarded = [];
    protected $attributes = [
        'status' => 0
    ];
    public function meeting()
    {
        return $this->belongsTo(Meeting::class);
    }

    public function statusOptions()
    {
        return [
            0 => 'Not Done',
            1 => 'Done',
        ];
    }

    public function getStatusAttribute($attribute)
    {
        return $this->statusOptions()[$attribute];
    }

}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use App\Subject;
use Illuminate\Http\Request;

class SubjectController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('view', \App\User::class);

        $subjects = Subject::where('company_id', auth()->user()->company_id)->get();
        $meetings = \App\Meeting::where('company_id', auth()->user()->company_id)->get();
        return view('subjects.index', compact('subjects', 'meetings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $this->authorize('view', \App\User::class);
        $subject = new Subject();
        $meetings = \App\Meeting::where('company_id', auth()->user()->company_id)->get();
        return view('subjects.create', compact('subject', 'meetings'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->authorize('view', \App\User::class);
        $validated = $this->validateRequest();
        $validated['status'] = 0;
        $validated['company_id'] = auth()->user()->company_id;
        $subject = Subject::create($validated);
        return redirect('subjects');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function show(Subject $subject)
    {
        //
        $this->authorize('view', \App\User::class);
        return view('subjects.show', compact('subject'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $this->authorize('view', \App\User::class);
        $subject = Subject::findOrFail($id);
        $meetings = \App\Meeting::where('company_id', auth()->user()->company_id)->get();
        
        return view('subjects.edit', compact('subject', 'meetings'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {
        //
        $this->authorize('view', \App\User::class);
        $subject->update($this->validateRequest());
        return view('subjects.show', compact('subject'));
        
    }

    /**
     * Update only status and editable fields
     * 
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function updateStatus(Request $request, $id)
    {
       $this->authorize('view', \App\User::class);
        $validated = request()->validate([
           "status" => "required|integer",
           "editable" => "required|integer",
        ]);
        $subject = Subject::findOrFail($id);
        $subject->update($validated);
        return response()->json(['success'=> 'updated']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subject $subject)
    {
        //
        $this->authorize('view', \App\User::class);
        $subject->delete();
        return redirect('subjects');
    }

    public function validateRequest()
    {
        return request()->validate([
            'title' => 'required|min:5',
            "meeting_id" => "required|integer", 
            "status" => "integer",
        ]);   
    }
}

resources/views/subjects/create.blade.php
@extends('layouts.app')

@section('title', 'Create New Subject')

@section('content')

<div class="row py-3">
    <h1> Create New Subject </h1>
    <hr>
</div>
<div class="row">
    <form action="{{ route('subjects.store') }}" method="post" enctype="multipart/form-data">
        @include('subjects.form')
        <button type="submit" class="btn btn-success">Create</button>
    </form>
</div>

@endsection

resources/views/subjects/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Subject')

@section('content')

<div class="row py-3">
    <h1> Edit subject </h1>
    <hr>
</div>
<div class="row">
    <form action="{{ route('subjects.update', ['subject'=> $subject ]) }}" method="post" enctype="multipart/form-data">
        @method('PATCH')
        @include('subjects.form')
        <button type="submit" class="btn btn-success">Update</button>
    <a href="{{url('subjects')}}" class="btn btn-link">Cancel</a>
    </form>
</div>

@endsection

resources/views/subjects/form.blade.php
@foreach ($errors->all() as $message)
<div class="alert alert-danger">
    <strong>Error!</strong>
    {{ $message }}
</div>
@endforeach
<div class="form-group">
    <label for="name">Subject name</label>
    <input type="text" class="form-control" name="title" id="title" value="{{ old('title') ?? $subject->title }}" autofocus>
    @if($errors->first('title'))
    <div class="alert alert-danger">
        <strong>Error!</strong>
        {{ $errors->first('title')}}
    </div>
    @endif
</div>

<div class="form-group">
    <label for="mail_domain">Choose meeting</label>
    <select name="meeting_id" id="meeting_id" class="form-control custom-select" >
        <option value="0">Select Meeting</option>
        @foreach ($meetings as $meeting)
        <option value="{{ $meeting->id }}" {{ isset($subject->meeting) && $subject->meeting->id === $meeting->id ? 'selected' : ''}}> {{ $meeting->title}} </option>    
        @endforeach
    </select>
    @if($errors->first('meeting'))
    <div class="alert alert-danger">
        <strong>Error!</strong>
        {{ $errors->first('meeting')}}
    </div>
    @endif
</div>
@if(Request::is('*/edit'))
<div class="form-group">
    <label for="registration_key">Subject Status</label>
    <select name="status" id="status" class="form-control">
            <option value="" disabled>Select subject status</option>
            @foreach($subject->statusOptions() as $statusOptionKey => $statusOptionValue)
            <option value="{{ $statusOptionKey }}" {{ $subject->status === $statusOptionValue ? 'selected' : '' }}>
                {{ $statusOptionValue }}</option>
            @endforeach
        </select>
    </select >
</div>
@endif


@csrf

resources/views/subjects/index.blade.php
@extends('layouts.app')

@section('title', 'Subject List')

@section('content')

<div class="row py-3">
  <h1> Subjects List </h1>
  <hr>
  @if(!$meetings->isEmpty())
  <a href="{{asset('/subjects/create')}}" role="button" class="btn btn-success btn-lg">Add subject</a>
  @else
  <div class="alert alert-danger" role="alert">
      Please create meetings in order to add subjects.
    </div>
  @endif
</div>
<div class="row">
  <table class="table  table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Status</th>
        <th scope="col">Meeting ID</th>
        <th scope="col">Manage</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($subjects as $subject)
      {{-- {{dd($subject)}} --}}
      <tr>
        <th scope="row"> {{$subject->id}} </th>
        <td>
          {{$subject->title}}
        </td>
        <td>
          {{ $subject->status}}
        </td>
        <td>
          {{isset($subject->meeting) ? $subject->meeting->title : 'No meeting'}}
        </td>
        <td>
            <a class="btn btn-info" href="subjects/{{ $subject->id }}" role="button">
              <i class="fa fa-eye"></i>
            </a>

          <a class="btn btn-success" href="subjects/{{ $subject->id }}/edit" role="button">
            <i class="fa fa-pencil"></i>

          </a>
        <button class="btn btn-danger btn-sm deleteMe" data-subject-id="{{ $subject->id }}" role="button">
            <i class="fa fa-trash"></i>
          </button>

        </td>
      </tr>
      @endforeach
    </tbody>
  </table>

  <script type="application/javascript">
    $(document).ready(function(){
       $('.deleteMe').on('click', function(){
         console.log('Clicked: ' +'/subjects/' + $(this).attr('data-subject-id'));
          $.ajax({
            url: "{{url('subjects')}}/" + $(this).attr('data-subject-id'),
            type: 'DELETE',
            headers: {
              "X-CSRF-TOKEN": "{{ csrf_token() }}",
            },
            success: function(){
              window.location.href = "subjects";
            },
            error: function(){
              window.location.href = "subjects";
            }
          });
       }) 
      
    });
</script>
</div>

@endsection

resources/views/subjects/show.blade.php
@extends('layouts.app')

@section('title', 'Subject')

@section('content')

<div class="row py-3">
    <h1> Details for subject #{{ $subject->id}} </h1>
    <hr>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                Details for subject #{{ $subject->id}}
            </div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Subject title</strong>
                    {{ $subject->title }}
                </li>
                <li class="list-group-item">
                    <strong>Subject on meeting</strong>
                    {{ $subject->meeting->title}}
                </li>
                <li class="list-group-item">
                    <strong>Status</strong>
                    {{ $subject->status }}
                </li>
            </ul>
            <div class="card-footer">
            <a href="{{url('subjects')}}" class="btn btn-link pull-left" role="button">Cancel</a>
            @if($subject->editable)
                <a href="{{ route('subjects.edit', ['subject'=> $subject ]) }}" class="btn btn-success pull-left"
                    role="button">
                    <i class="fa fa-pencil"></i>
                </a>
            @endif
                <form class="form-inline" action="{{ route('subjects.destroy', ['subject'=> $subject ]) }}"
                    method="post" enctype="multipart/form-data">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-danger">
                        <i class="fa fa-trash"></i>
                    </button>
                </form>
            </div>
        </div>

    </div>
</div>

@endsection