routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('dashboard');   
})->middleware('auth');



Route::get('invite', 'InviteController@invite')->name('invite')->middleware('auth');
Route::post('invite', 'InviteController@process')->name('process')->middleware('auth');
Route::get('accept/{token}', 'InviteController@accept')->name('accept');


Route::get('dashboard', 'DashboardController@index')->middleware('auth');
Route::resource('tasks', 'TasksController')->middleware('auth');
Route::post('tasks/updateStatus/{id}', 'TasksController@updateStatus')->name('tasks.updateStatus')->middleware('auth');
Route::post('tasks/assignUser/{id}', 'TasksController@assignUser')->name('tasks.assignUser')->middleware('auth');

Route::resource('meetings', 'MeetingController')->middleware('auth');
Route::resource('users', 'UsersController')->middleware('auth');
Route::resource('companies', 'CompanyController')->middleware('auth');
Route::resource('subjects', 'SubjectController')->middleware('auth');
Route::post('subjects/updateStatus/{id}', 'SubjectController@updateStatus')->name('subjects.updateStatus')->middleware('auth');

Auth::routes();
Route::get('register.admin', 'Auth\RegisterController@admin')->name('register.admin');
Route::post('register.createAdmin', 'Auth\RegisterController@createAdmin')->name('register.createAdmin');

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    // Scope Status
    // In progress
    // Done 
    // Not Done 
    // Missed Deadline
    // Other
    protected $guarded = [];
    protected $attributes = [
        'status' => 0
    ];
    public function setDeadlineAttribute($value)
    {
        $time = strtotime($value);
        $this->attributes['deadline'] = date('Y-m-d H:i:s', $time);
    }

    public function getDeadlineAttribute()
    {
        if (isset($this->attributes['deadline'])) { 
            return date("Y-m-d H:i:s", strtotime($this->attributes['deadline']));
        }
        // Nothing to return maybe when creating task
        return '';
    }

    public function getStatusAttribute($attribute)
    {
        return $this->statusOptions()[$attribute];
    }

    public function statusOptions()
    {
        return [
            0 => 'Not Assigned',
            1 => 'In Progress',
            2 => 'Done',
            3 => 'Missed Deadline',
        ];
    }

    public function statusColoring($val)
    {
        $colors = [
            'Not Assigned' => "secondary",
            'In Progress' => "warning",
            'Done' => "success",
            'Missed Deadline' => "danger",
        ];
        return $colors[$val];    
    }

    public function user()
    {
       return $this->belongsTo(User::class);
    }

    public function meeting()
    {
        return $this->belongsTo(Meeting::class);
    }
}

app/Http/Controllers/TasksController.php
<?php


namespace App\Http\Controllers;

use App\Task;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class TasksController extends Controller
{
    private $meetings;
    public function __construct()
    {
        $this->meetings = \App\Meeting::all(); 
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // 
        $tasks = Task::where('company_id', auth()->user()->company_id)->get();
        return view('tasks.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $this->authorize('create', \App\Task::class);
        $task = new Task();
        $user = auth()->user();
        $users = \App\User::where('company_id', auth()->user()->company_id)->get();
        $meetings = collect($this->meetings)->filter(function($value, $key)use($user){
            return $value->company_id == $user->company_id;
        });
        return view('tasks.create', compact('task', 'users','meetings'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->authorize('create', \App\Task::class);
        $validated = $this->validateRequest();
        // Automatic company id assignement to creating users
        $validated['company_id'] = auth()->user()->company_id;
        $task = Task::create($validated);
        return redirect('tasks');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $this->authorize('view', auth()->user(),\App\Task::class);
        $task = Task::findOrFail($id);
        return view('tasks.show', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::findOrFail($id);
        $user = auth()->user();
        $users = \App\User::where('company_id', $user->company_id)->get();
        $meetings = collect($this->meetings)->filter(function($value, $key)use($user){
            return $value->company_id == $user->company_id;
        });
        return view('tasks.edit', compact('task','users', 'meetings'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $task = Task::findOrFail($id);
        $task->update($this->validateRequest());
        return redirect('tasks/'. $id);
    }

    /**
     * Update only status and editable fields
     * 
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

     public function updateStatus(Request $request, $id)
     {
         $validated = request()->validate([
            "status" => "required|integer",
            "editable" => "required|integer",
         ]);
         $task = Task::findOrFail($id);
         $task->update($validated);
         return response()->json(['success'=> 'updated']);
     }
         /**
     * Update only status and user_id fields
     * 
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function assignUser(Request $request, $id)
    {
        $validated = request()->validate([
           "status" => "required|integer",
           "user_id" => "required|integer",
        ]);
        $task = Task::findOrFail($id);
        $task->update($validated);
        return response()->json(['success'=> 'User assigned']);
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::findOrFail($id);
        $task->delete();

        return redirect('/tasks');
    }

    public function validateRequest()
    {
        return request()->validate([
            'description' => 'required|min:5',
            "deadline" => "required|date_format:Y-m-d H:i:s", //date_format:d/m/Y h:i A
            "user_id" => 'integer',
            "status" => "required",
            "meeting_id" => 'nullable',
        ]);
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('title', 'Create New Task')

@section('content')

<div class="row py-3">
    <h1> Create New Task </h1>
    <hr>
</div>
<div class="row">
    <form action="{{ route('tasks.store') }}" method="post" enctype="multipart/form-data">
        @include('tasks.form')
        <button type="submit" class="btn btn-success">Create</button>
    </form>
</div>

@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Task')

@section('content')

<div class="row py-3">
    <h1> Edit Task </h1>
    <hr>
</div>
<div class="row">
    <form action="{{ route('tasks.update', ['task'=> $task ]) }}" method="post" enctype="multipart/form-data">
        @method('PATCH')
        @include('tasks.form')
        <button type="submit" class="btn btn-success">Update</button>
    </form>
</div>

@endsection

resources/views/tasks/form.blade.php
{{-- DatePicker https://tempusdominus.github.io/bootstrap-4/Usage/ --}}

@foreach ($errors->all() as $message)
<div class="alert alert-danger">
    <strong>Error!</strong>
    {{ $message }}
</div>
@endforeach
<div class="form-group">
    <label for="description">Description</label>
    <input type="text" class="form-control" name="description" id="description"
        value="{{ old('description') ?? $task->description }}" autofocus>
    @if($errors->first('description'))
    <div class="alert alert-danger">
        <strong>Error!</strong>
        {{ $errors->first('description')}}
    </div>
    @endif
</div>

<div class="form-group">
    <label for="deadline">Deadline</label>
    {{-- jQuery DateTime Plugin --}}
    {{-- <input type="date" class="form-control" id="deadline" value="{{ old('deadline') ?? $task->deadline }}"> --}}
    {{-- @dump($task) --}}
    <div class="input-group date" data-target-input="nearest">
        <input type="text" class="form-control datetimepicker-input" data-target="#deadline"
            value="{{ old('deadline') ?? $task->deadline }}" name="deadline" id="deadline" />
        <div class="input-group-append" data-target="#deadline" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
        </div>
    </div>
    @if($errors->first('deadline'))
    <div class="alert alert-danger">
        <strong>Error!</strong>
        {{ $errors->first('deadline')}}
    </div>
    @endif
</div>

{{-- User to be assigned --}}
<div class="form-group">
    <label for="Users">
        Assign user for task:
    </label>
    <br>
    <select name="user_id" id="user_id" class="form-control">
        <option value="0">Not assigned</option>
        @foreach ($users as $user)
        @if(auth()->user()->company_id == $user->company_id)
        <option value="{{$user->id}}" {{$user->id == $task->user_id ? 'selected': ''}}>{{$user->name}}</option>
        @endif
        @endforeach
    </select>
</div>

<div class="form-group">
    <label for="mail_domain">Choose meeting</label>
    <select name="meeting_id" id="meeting_id" class="form-control custom-select">
        <option value="0">Select Meeting</option>
       @foreach ($meetings as $meeting)
         <option value="{{ $meeting->id }}"
            {{ isset($task->meeting) && $task->meeting->id === $meeting->id ? 'selected' : ''}}>
            {{ $meeting->title}} </option>
        @endforeach
    </select>
    @if($errors->first('meeting'))
    <div class="alert alert-danger">
        <strong>Error!</strong>
        {{ $errors->first('meeting')}}
    </div>
    @endif
</div>

<div class="form-group">
    <label for="status">Status</label>
    <br>
    <select name="status" id="status" class="form-control">
        <option value="" disabled>Select task status</option>

        @foreach($task->statusOptions() as $statusOptionKey => $statusOptionValue)
        <option value="{{ $statusOptionKey }}" {{ $task->status === $statusOptionValue ? 'selected' : '' }}>
            {{ $statusOptionValue }}</option>
        @endforeach
    </select>
</div>
<a href="{{url('tasks')}}" class="btn btn-link">Cancel</a>
@csrf
<script type="application/javascript">
    $(function () {
            $('#deadline').datetimepicker({
               format:'Y-m-d H:i:s' // defaultDate: "{{ old('deadline') ?? $task->deadline}}"
            });
        });
</script>

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('title', 'Task List')

@section('content')

<div class="row py-3">
  <h1> Tasks List </h1>
  <hr>
  @can('create', \App\Task::class)
  <a href="tasks/create" role="button" class="btn btn-success btn-lg">Add Task</a>
  @endcan
</div>
<div class="row">
  <table class="table  table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">User assigned</th>
        <th scope="col">Status</th>
        <th scope="col">Meeting</th>
        <th scope="col">Deadline</th>
        <th scope="col">Description</th>
        <th scope="col">Manage</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($tasks as $task)
      {{-- {{ dd($task->user->id == auth()->user()->id) }} --}}
      @can('view',$task) 
      <tr>
        <th scope="row"> {{ $task->id }} </th>
        <td> {{ isset($task->user) ? $task->user->name : 'Not assigned'  }} </td>
        <td>
          <h5>
            <span class="badge badge-{{$task->statusColoring($task->status) }}">
              {{ $task->status }}
            </span>
          </h5>
        </td>
        <td>{{ isset($task->meeting) ? $task->meeting->title : 'None'}}</td>
        <td>{{ $task->deadline }}</td>
        <td> {{ $task->description }} </td>
        <td>
          <a class="btn btn-info" href="tasks/{{ $task->id }}" role="button">
            <i class="fa fa-eye"></i>
          </a>

          @can('delete', $task)
          @if($task->editable)
          <a class="btn btn-success" href="tasks/{{ $task->id }}/edit" role="button">
            <i class="fa fa-pencil"></i>
          </a>
          @endif
          <button class="btn btn-danger btn-sm deleteMe" data-task-id="{{ $task->id }}" role="button">
            <i class="fa fa-trash"></i>
          </button>
          @endcan
        </td>
      </tr>
      @endcan
      @endforeach
    </tbody>
  </table>


</div>

<script type="application/javascript">
  $(document).ready(function(){
    console.log('ready to work')
     $('.deleteMe').on('click', function(){
       console.log('Clicked: ' +'/tasks/' + $(this).attr('data-task-id'));
        $.ajax({
          url: "{{ asset('/tasks') }}/" + $(this).attr('data-task-id'),
          type: 'DELETE',
          headers: {
            "X-CSRF-TOKEN": "{{ csrf_token() }}",
          },
          success: function(){
            window.location.href = "tasks";
          },
          error: function(){
            window.location.href = "tasks";
          }
        });
     }) // Delete Me 
     
  });
</script>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('title', 'Task')

@section('content')

<div class="row py-3">
    <h1> Details for #{{ $task->id}} </h1>
    <hr>
</div>
<div class="row">
   
</div>
<div class="row">

    <div class="col-12">
        <div class="card">
            <div class="card-header">
                Details for #{{ $task->id}}
            </div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Description: </strong>
                    {{ $task->description }}</li>
                <li class="list-group-item"><strong>Meeting: </strong>
                        {{ isset($task->meeting) ? $task->meeting->title : 'None' }}</li>
                <li class="list-group-item"><strong>User assigned:</strong>
                    {{ isset($task->user) ? $task->user->name : 'Not assigned'}}</li>
                <li class="list-group-item"><strong>Deadline: </strong>
                    {{ $task->deadline}}
                </li>
                <li class="list-group-item"><strong>Status:</strong>
                    <h5>
                        <span class="badge badge-{{$task->statusColoring($task->status) }}">
                            {{$task->status}}
                        </span>
                    </h5>
                </li>
            </ul>
            <div class="card-footer">
                    <a href="{{url('tasks')}}" class="btn btn-link pull-left">Back</a>
                    
                    @can('delete', $task)
                    @if($task->editable)
                    <a href="{{ route('tasks.edit', ['task'=> $task ]) }}" class="btn btn-success pull-left" role="button">
                            <i class="fa fa-pencil"></i>
                        </a>
                    @endif
                        <form class="form-inline" action="{{ route('tasks.destroy', ['task'=> $task ]) }}" method="post" enctype="multipart/form-data">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger">
                                <i class="fa fa-trash"></i>
                            </button>
                        </form>
                    @endcan
            </div>
        </div>
    </div>
</div>

<script type="application/javascript">
    $(function () {
        var statuses = {
            'Not Assigned' : "secondary",
            'In Progress' : "warning",
            'Done' : "success",
            'Missed Deadline' : "danger",
        };
        // Set status for shown task
        $('.badge').addClass('badge-' + statuses["{{$task->status}}"]);
               
    });
</script>
@endsection